language: node_js
node_js:
- "16.13.2"

before_script:
  - cd QA-api
  - npm install

script:
  - ls -la
  - chmod +x ./node_modules/.bin/cross-env
  - sudo ./node_modules/.bin/cross-env NODE_ENV=test npm test
