language: node_js
node_js:
- "16.13.2"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run QA-api/test/postman_collection.json -e QA-api/test/environment_collection.json