language: node_js
node_js:
- 17
install:
- npm install -g mocha
- npm install chai
- npm install chai-http
- npm install express
- npm install --save-dev cross-env

script:
  - cross-env NODE_ENV=test mocha --recursive --exit
